### PR TITLE
stochastic volatility model using simulated moments

### PR DESCRIPTION
**Pull request by mcreel**
This code shows how one can compute an estimator that is similar to the method of simulated moments. It is a little time consuming, but works quite well.

### CODE REVIEW

**Comment by tpapp** [comment]
I appreciate that you contributed this. I am quite busy at the moment, but will review it soon.

**Comment by mcreel** [comment]
For purposes of comparison, this same model estimated by simulated moments (indirect inference) is here: https://github.com/mcreel/Econometrics/blob/master/Examples/SBEM/EstimateStochasticVolatilityModel.jl

**Comment by tpapp** [comment]
Forgot about this, sorry. Merging now.

**Comment by mcreel** [comment]
That still works? I seem to recall an API change after that was written, which I assumed would break it. I will have another look at it before long.

**Comment by tpapp** [comment]
It is currently not in the tests. I will update it, following up on API changes, and will ask you for a review in the PR.

**Comment by mcreel** [comment]
Great! Thanks.

**Pull request merged**
